baseurl = "https://pindasdata.netlify.app"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Pinda's Data"
theme = "hugo-theme-dream"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

copyright = "&copy; 2018. All rights reserved."

googleAnalytics = "UA-116203285-2"

disqusShortname = "pindasdatav2"

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    
[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Eduardo Ochetski"
  # description = ""
  avatar = "/img/profile2.jpg"
  motto = "Meu lugar na internet, sobre muitas coisas e R." 
  # categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "ehellas@gmail.com"
  twitter = "pinduzera"
  facebook = "eduardo.ochetskihellas"
  instagram = "pinduzera/"
  # mastodon = ""
  linkedin = "eduardo-ochetski-hellas-8b0771110/"
  github = "pinduzera/"
  stackoverflow = "5322743/ochetski"
  # codepen = ""

  siteStartYear = 2018

  favicon = "favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml", "R", "Rmd", "Python", "yaml", "toml"]
   highlightjsTheme = "gruvbox-light"
   highlightjsThemeDark = "monokai-sublime"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
