baseurl = "pindasdata.netlify.app"
languageCode = "pt"
defaultContentLanguage = "pt"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

#copyright = "&copy; 2018. All rights reserved."

#googleAnalytics = "251307803"

#disqusShortname = "pindasdatav2"

# enableRobotsTXT = true
#[languages]
#  [languages.pt]
#    languageName = "Portuguese"
#    weight = 1
#    contentDir = "content/portuguese"
#    motto = "My place in the internet, about many things and R."

#  [languages.en]
#    languageName = "English"
#    weight = 2
#    contentDir = "content/english"
#    motto = "Meu lugar na internet, sobre muitas coisas e R."

    
[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Eduardo Ochetski"
  # description = ""
  avatar = "/img/profile2.jpg"
  # motto = "Meu lugar na internet, sobre muitas coisas e R."
  # categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "ehellas@gmail.com"
  twitter = "pinduzera"
  facebook = "eduardo.ochetskihellas"
  instagram = "pinduzera/"
  # mastodon = ""
  linkedin = "eduardo-ochetski-hellas-8b0771110/"
  github = "pinduzera/"
  stackoverflow = "5322743/ochetski"
  # codepen = ""

  siteStartYear = 2018

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml", "R", "Rmd", "Python", "yaml", "toml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  # enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
